Repository Automattic/studio, pull requests merged in 2024-09, with the labels that each got.

#476 Add language switcher in user settings modal
  src/components/auth-provider.tsx
  src/components/default-error-fallback.tsx
  src/components/language-picker.tsx
  src/components/root.tsx
  src/components/user-settings.tsx
  src/hooks/tests/use-chat-context.test.tsx
  src/hooks/use-expiration-date.ts
  src/hooks/use-i18n-data.tsx
  src/hooks/use-localization-support.ts
  src/index.ts
  src/ipc-handlers.ts
  src/ipc-types.d.ts
  src/lib/locale-node.ts
  src/lib/locale.ts
  src/lib/site-language.ts
  src/lib/tests/locale.test.ts
  src/preload.ts
  src/renderer.ts
  src/storage/storage-types.ts
  src/translations/index.ts
Labels: [Type] Feature Request

#495 Studio: Fix all demo sites are marked as updating when one is updated
  src/components/content-tab-snapshots.tsx
  src/components/tests/content-tab-snapshots.test.tsx
  src/hooks/tests/use-update-demo-site.test.tsx
  src/hooks/use-update-demo-site.tsx
Labels: Studio App

#502 Update: translations for 1.1.1
  src/translations/studio-ar.jed.json
  src/translations/studio-de.jed.json
  src/translations/studio-es.jed.json
  src/translations/studio-fr.jed.json
  src/translations/studio-he.jed.json
  src/translations/studio-id.jed.json
  src/translations/studio-it.jed.json
  src/translations/studio-ja.jed.json
  src/translations/studio-ko.jed.json
  src/translations/studio-nl.jed.json
  src/translations/studio-pl.jed.json
  src/translations/studio-pt-br.jed.json
  src/translations/studio-ru.jed.json
  src/translations/studio-sv.jed.json
  src/translations/studio-tr.jed.json
  src/translations/studio-uk.jed.json
  src/translations/studio-vi.jed.json
  src/translations/studio-zh-cn.jed.json
  src/translations/studio-zh-tw.jed.json
Labels: [Status] Needs Review

#504 Ensure all strings are updated when switching language
  src/hooks/use-i18n-data.tsx
  src/ipc-handlers.ts
  src/main-window.ts
  src/menu.ts
  src/preload.ts
Labels: [Status] Needs Review

#501 [Tooling] Update Ruby dependencies
  Gemfile
  Gemfile.lock
Labels: Tooling

#513 Release 1.1.1-beta2
  package-lock.json
  package.json
Labels: [Status] Needs Review

#514 Ensure sites are always stopped
  src/lib/site-server-process.ts
  src/site-server.ts
Labels: [Status] Needs Review, Studio Compatibility Boost

#519 Mount filesystems again when rotating PHP runtime instance
  vendor/wp-now/src/wp-now.ts
Labels: [Status] Needs Review, Studio Compatibility Boost

#521 Mock `executeWpCliCommand` function to avoid generating console error logs
  src/lib/import-export/tests/import/importer/default-importer.test.ts
  src/lib/import-export/tests/import/importer/local-importer.test.ts
  src/lib/import-export/tests/import/importer/playground-importer.test.ts
Labels: [Type] Enhancement, [Status] Needs Review

#522 Release 1.1.1-beta3
  package-lock.json
  package.json
Labels: [Status] Needs Review

#517 Use site's PHP version when running WP-CLI commands
  src/lib/wp-cli-process-child.ts
  src/lib/wp-cli-process.ts
  src/site-server.ts
  vendor/wp-now/src/execute-wp-cli.ts
Labels: [Type] Bug, [Status] Needs Review, Studio Compatibility Boost, Groundskeeping

#528 Update playground packages to v0.9.39
  package-lock.json
  package.json
Labels: [Type] Enhancement, [Status] Needs Review, Studio Compatibility Boost

#545 Improvements related to Assistant prompt limit
  src/components/content-tab-assistant.tsx
  src/constants.ts
  src/hooks/use-prompt-usage.tsx
Labels: [Type] Enhancement, [Status] Needs Review, Studio AI Assistant

#546 Fix parsing of Assistant usage quota
  src/components/welcome-message-prompt.tsx
  src/hooks/tests/use-prompt-usage.test.ts
  src/hooks/use-prompt-usage.tsx
Labels: [Type] Bug, [Status] Needs Review, Studio AI Assistant

#547 Apply formatting to `vendor/wp-now` files
  .prettierignore
  vendor/wp-now/.prettierignore
  vendor/wp-now/public/with-node-version.js
  vendor/wp-now/src/add-trailing-slash.ts
  vendor/wp-now/src/config.ts
  vendor/wp-now/src/constants.ts
  vendor/wp-now/src/download.ts
  vendor/wp-now/src/execute-php.ts
  vendor/wp-now/src/execute-wp-cli.ts
  vendor/wp-now/src/get-sqlite-path.ts
  vendor/wp-now/src/get-wordpress-versions-path.ts
  vendor/wp-now/src/get-wp-cli-path.ts
  vendor/wp-now/src/get-wp-cli-tmp-path.ts
  vendor/wp-now/src/get-wp-now-path.ts
  vendor/wp-now/src/get-wp-now-tmp-path.ts
  vendor/wp-now/src/github-codespaces.ts
  vendor/wp-now/src/main.ts
  vendor/wp-now/src/port-finder.ts
  vendor/wp-now/src/run-cli.ts
  vendor/wp-now/src/start-server.ts
  vendor/wp-now/src/tests/add-trailing-slash.spec.ts
  vendor/wp-now/src/tests/execute-php.spec.ts
  vendor/wp-now/src/tests/github-codespaces.spec.ts
  vendor/wp-now/src/tests/wp-now.spec.ts
  vendor/wp-now/src/wp-now.ts
  vendor/wp-now/src/wp-playground-wordpress/get-plugin-file.ts
  vendor/wp-now/src/wp-playground-wordpress/has-index-file.ts
  vendor/wp-now/src/wp-playground-wordpress/is-plugin-directory.ts
  vendor/wp-now/src/wp-playground-wordpress/is-theme-directory.ts
  vendor/wp-now/src/wp-playground-wordpress/is-valid-wordpress-version.ts
  vendor/wp-now/src/wp-playground-wordpress/is-wordpress-develop-directory.ts
  vendor/wp-now/src/wp-playground-wordpress/is-wordpress-directory.ts
  vendor/wp-now/src/wp-playground-wordpress/is-wp-content-directory.ts
  vendor/wp-now/src/wp-playground-wordpress/read-file-head.ts
  vendor/wp-now/src/wp-playground-wordpress/tests/get-plugin-file.spec.ts
  vendor/wp-now/src/wp-playground-wordpress/tests/is-valid-wordpress-version.test.ts
  vendor/wp-now/vite.config.ts
Labels: [Pri] Low, [Type] Janitorial, [Status] Needs Review

#510 Enable support for symlinks
  src/lib/symlink-manager.ts
  src/lib/tests/symlink-manage.test.ts
  vendor/wp-now/src/start-server.ts
  vendor/wp-now/src/wp-now.ts
Labels: [Type] Enhancement, [Status] Needs Review, Studio Compatibility Boost

#554 Enable React Devtools
  package-lock.json
  package.json
  src/main-window.ts
Labels: [Type] Enhancement, [Status] Needs Review

#549 Allow opening relative paths returned by the assistant in the user's IDE
  src/components/assistant-code-block.tsx
  src/components/tests/assistant-code-block.test.tsx
  src/index.css
  src/ipc-handlers.ts
  src/preload.ts
  tailwind.config.js
Labels: [Type] Enhancement, [Status] Needs Review, Studio AI Assistant

#550 Improve performance of Assistant tab
  src/components/content-tab-assistant.tsx
  src/hooks/use-assistant.ts
  src/hooks/use-send-feedback.ts
Labels: [Type] Enhancement, [Status] Needs Review, Studio AI Assistant

#555 Override default `umask` in PHP
  vendor/wp-now/src/wp-now.ts
Labels: [Type] Bug, [Status] Needs Review, Studio Compatibility Boost

#557 Restore the Assistant chat input per site
  src/components/ai-clear-history-reminder.tsx
  src/components/ai-input.tsx
  src/components/content-tab-assistant.tsx
  src/components/root.tsx
  src/components/tests/ai-clear-history-reminder.test.tsx
  src/components/tests/ai-input.test.tsx
  src/components/tests/content-tab-assistant.test.tsx
  src/hooks/tests/use-chat-input.test.tsx
  src/hooks/use-chat-input.tsx
Labels: [Type] Bug, [Status] Needs Review, Studio AI Assistant

#532 Remove system-wide user authentication with a more typical approach
  e2e/sites.test.ts
  patches/@php-wasm+universal+0.9.39.patch
  src/components/content-tab-import-export.tsx
  src/components/content-tab-overview.tsx
  src/components/header.tsx
  src/ipc-handlers.ts
  src/preload.ts
  vendor/wp-now/src/start-server.ts
Labels: [Type] Bug, Studio App, [Status] Needs Review

#559 Run SQLite import WP-CLI command with default PHP version
  src/lib/import-export/import/importers/importer.ts
  src/lib/import-export/tests/import/importer/default-importer.test.ts
  src/site-server.ts
Labels: [Type] Bug, [Status] Needs Review, Studio Import & Export

#560 Override `umask` value using a preload file loaded by Playground
  vendor/wp-now/src/wp-now.ts
Labels: [Type] Bug, [Status] Needs Review

#561 Update playground to version 0.9.44
  package-lock.json
  package.json
  vendor/wp-now/src/start-server.ts
Labels: [Status] Needs Review, Studio Compatibility Boost

#566 Fix broken symlinks prevents the site to be started
  src/lib/symlink-manager.ts
  src/lib/tests/symlink-manage.test.ts
Labels: [Type] Bug, [Status] Needs Review, Studio Compatibility Boost

#567 Update scroll logic in Assistant tab
  src/components/chat-message.tsx
  src/components/content-tab-assistant.tsx
Labels: [Type] Enhancement, [Status] Needs Review, Studio AI Assistant
