Repository Automattic/studio, pull requests merged in 2024-07, with the labels that each got.

#325 Studio: fix error with new message id
  src/components/content-tab-assistant.tsx
  src/hooks/use-assistant.ts
Labels: Studio AI Assistant

#323 test: Revert rudimentary console filtering
  jest-setup.ts
Labels: [Type] Janitorial

#135 Create DMGs for x64 and arm64 builds
  .buildkite/commands/prepare-environment.sh
  .buildkite/pipeline.yml
  fastlane/Fastfile
  package.json
  scripts/make-dmg.mjs
Labels: Studio App

#267 Studio: Add animation when we receive a message UI
  src/components/assistant-code-block.tsx
  src/components/assistant-thinking.tsx
  src/components/chat-message.tsx
  src/components/content-tab-assistant.tsx
  src/components/tests/content-tab-assistant.test.tsx
  src/hooks/use-assistant-api.ts
Labels: Studio AI Assistant

#349 Studio: Fix the alignment on the logged out view
  src/components/chat-message.tsx
Labels: [Type] Bug

#340 Studio: fix setting menu not open if no sites
  src/components/app.tsx
  src/components/main-sidebar.tsx
Labels: [Type] Bug

#344 Studio: Snapshot counter not updating in settings when a site is deleted
  src/components/content-tab-snapshots.tsx
  src/components/delete-site.tsx
  src/components/root.tsx
  src/components/tests/content-tab-settings.test.tsx
  src/components/tests/content-tab-snapshots.test.tsx
  src/components/user-settings.tsx
  src/hooks/tests/use-delete-snapshot.test.ts
  src/hooks/tests/use-delete-snapshot.test.tsx
  src/hooks/tests/use-fetch-snapshots.test.ts
  src/hooks/tests/use-fetch-snapshots.test.tsx
  src/hooks/tests/use-site-usage.test.ts
  src/hooks/tests/use-site-usage.test.tsx
  src/hooks/tests/use-update-demo-site.test.tsx
  src/hooks/use-archive-site.ts
  src/hooks/use-delete-snapshot.ts
  src/hooks/use-fetch-snapshots.ts
  src/hooks/use-site-details.tsx
  src/hooks/use-site-usage.ts
  src/hooks/use-snapshots.tsx
  src/hooks/use-update-demo-site.tsx
Labels: [Type] Bug

#355 Studio: Add linux instruction for building studio
  docs/code-contributions.md
Labels: Studio App

#351 Studio: Add a component that handles a site import
  package-lock.json
  package.json
  src/ipc-handlers.ts
  src/lib/import-export/import/handlers/backup-handler-factory.ts
  src/lib/import-export/import/handlers/backup-handler-sql.ts
  src/lib/import-export/import/handlers/backup-handler-tar-gz.ts
  src/lib/import-export/import/handlers/backup-handler-zip.ts
  src/lib/import-export/import/import-manager.ts
  src/lib/import-export/import/importers/importer.ts
  src/lib/import-export/import/importers/index.ts
  src/lib/import-export/import/types.ts
  src/lib/import-export/import/validators/index.ts
  src/lib/import-export/import/validators/jetpack-validator.ts
  src/lib/import-export/import/validators/sql-validator.ts
  src/lib/import-export/import/validators/validator.ts
  src/lib/import-export/tests/import/handlers/backup-handler.test.ts
  src/lib/import-export/tests/import/import-manager.test.ts
  src/lib/import-export/tests/import/importer/default-importer.test.ts
  src/lib/import-export/tests/import/validators/jetpack-validator.test.ts
  src/lib/import-export/tests/import/validators/sql-validator.test.ts
  src/preload.ts
Labels: Studio Import & Export

#362 Studio: Replace button loading indicator with full window one
  e2e/sites.test.ts
  src/components/add-site.tsx
  src/components/onboarding.tsx
  src/components/site-content-tabs.tsx
  src/components/site-loading-indicator.tsx
  src/components/site-menu.tsx
  src/components/tests/add-site.test.tsx
  src/hooks/use-add-site.ts
  src/hooks/use-site-details.tsx
  src/ipc-types.d.ts
Labels: [Pri] Normal

#371 Studio: Disable 'Add site' button when site is being added
  src/components/add-site.tsx
Labels: Reviewer can merge

#365 Studio: Add export site
  src/components/content-tab-import-export.tsx
  src/ipc-handlers.ts
  src/lib/fs-utils.ts
  src/lib/generate-site-name.ts
  src/lib/import-export/export/export-manager.ts
  src/lib/import-export/export/exporters/default-exporter.ts
  src/lib/import-export/export/exporters/index.ts
  src/lib/import-export/export/exporters/sql-exporter.ts
  src/lib/import-export/export/types.ts
  src/lib/import-export/export/validators/wordpress-validator.ts
  src/lib/import-export/import/import-manager.ts
  src/lib/import-export/tests/export/export-manager.test.ts
  src/lib/import-export/tests/export/exporters/default-exporter.test.ts
  src/lib/import-export/tests/export/validators/wordpress-export-validator.test.ts
  src/preload.ts
Labels: Studio Import & Export

#369 Add import tab UI for existing sites
  src/components/content-tab-import-export.tsx
  src/components/progress-bar.tsx
  src/components/tests/content-tab-import-export.test.tsx
  src/hooks/tests/use-drag-and-drop-file.test.tsx
  src/hooks/use-confirmation-dialog.ts
  src/hooks/use-drag-and-drop-file.ts
  src/hooks/use-site-details.tsx
  src/ipc-types.d.ts
Labels: Studio Import & Export

#370 Studio: Add events for import/export
  src/components/content-tab-import-export.tsx
  src/ipc-handlers.ts
  src/lib/import-export/export/events.ts
  src/lib/import-export/export/export-manager.ts
  src/lib/import-export/export/exporters/default-exporter.ts
  src/lib/import-export/export/exporters/sql-exporter.ts
  src/lib/import-export/export/types.ts
  src/lib/import-export/export/validators/wordpress-validator.ts
  src/lib/import-export/import/events.ts
  src/lib/import-export/import/handlers/backup-handler-factory.ts
  src/lib/import-export/import/handlers/backup-handler-sql.ts
  src/lib/import-export/import/handlers/backup-handler-tar-gz.ts
  src/lib/import-export/import/handlers/backup-handler-zip.ts
  src/lib/import-export/import/import-manager.ts
  src/lib/import-export/import/importers/importer.ts
  src/lib/import-export/import/validators/jetpack-validator.ts
  src/lib/import-export/import/validators/sql-validator.ts
  src/lib/import-export/import/validators/validator.ts
  src/lib/import-export/tests/export/export-manager.test.ts
  src/lib/import-export/tests/import/import-manager.test.ts
  src/lib/import-export/types.ts
  src/preload.ts
Labels: Studio Import & Export

#376 Studio: export progress UI
  src/components/content-tab-import-export.tsx
  src/components/progress-bar.tsx
  src/components/root.tsx
  src/components/tests/content-tab-import-export.test.tsx
  src/hooks/tests/use-import-export.tsx
  src/hooks/use-import-export.tsx
  src/index.ts
  src/ipc-handlers.ts
  src/lib/import-export/export/events.ts
  src/lib/import-export/export/export-manager.ts
  src/lib/import-export/export/exporters/default-exporter.ts
  src/lib/import-export/export/generate-backup-filename.ts
  src/lib/import-export/export/types.ts
  src/preload.ts
Labels: Studio Import & Export

#401 Show complete export message in progress bar
  src/hooks/tests/use-import-export.tsx
  src/hooks/use-import-export.tsx
Labels: [Type] Enhancement
