Repository Automattic/studio, pull requests merged in 2024-05, with the labels that each got.

#74 fix: Avoid usage API requests while offline
  src/hooks/tests/use-site-usage.test.ts
  src/hooks/use-site-usage.ts
Labels: [Type] Bug

#75 Make drag triggers consistent across the app
  src/components/app.tsx
  src/components/main-sidebar.tsx
  src/components/onboarding.tsx
  src/components/site-content-tabs.tsx
  src/components/site-menu.tsx
Labels: [Type] Enhancement

#69 Fix path resolution of available site translations file
  src/lib/site-language.ts
  src/lib/tests/site-language.test.ts
  src/storage/paths.ts
Labels: [Type] Bug

#77 Local Environment: Dont send event if destroyed
  src/ipc-handlers.ts
Labels: [Status] Needs Review

#68 fix: Failed site creation resets the directory
  jest-setup.ts
  src/__mocks__/@sentry/electron/main.ts
  src/__mocks__/electron.ts
  src/__mocks__/fs.ts
  src/ipc-handlers.ts
  src/lib/tests/locale.test.ts
  src/lib/tests/passwords.test.ts
  src/lib/tests/sanitize-for-logging.test.ts
  src/lib/tests/site-language.test.ts
  src/lib/tests/sort-sites.test.ts
  src/storage/tests/user-data.test.ts
  src/tests/ipc-handlers.test.ts
  src/tests/site-server.test.ts
Labels: [Type] Bug

#80 test: Fix ipc-handlers mocks
  src/__mocks__/electron.ts
  src/tests/ipc-handlers.test.ts
Labels: [Type] Janitorial

#78 Remove local userpaths from error reporting
  src/lib/sanitize-for-logging.ts
  src/lib/tests/sanitize-for-logging.test.ts
  src/storage/user-data.ts
Labels: [Status] Needs Review

#81 Update dependabot dependencies
  package-lock.json
  package.json
Labels: [Status] Needs Review

#83 Update quick actions layout
  src/components/buttons-section.tsx
  src/components/content-tab-overview.tsx
  src/components/content-tab-snapshots.tsx
Labels: [Status] Needs Review

#79 Fix: Cannot create BrowserWindow before app is ready
  src/index.ts
Labels: [Type] Bug

#70 Fix incorrect preferred locale selection with multiple languages configured
  src/__mocks__/electron.ts
  src/index.ts
  src/lib/locale.ts
  src/lib/tests/locale.test.ts
  src/lib/tests/site-language.test.ts
Labels: [Type] Bug

#85 Add Windows Signing
  .buildkite/commands/build-windows-dev.ps1
  .buildkite/commands/post-process-binary-for-distribution.sh
  .buildkite/pipeline.yml
  .github/workflows/build-installer.yml
  Gemfile.lock
  fastlane/Fastfile
  forge.config.ts
  package.json
  scripts/generate-releases-manifest.mjs
  scripts/prepare-dev-build-version.mjs
Labels: [Platform] Windows

#91 build: Suppress sentry-webpack-plugin logs
  webpack.plugins.ts
Labels: [Type] Janitorial

#92 fix: Improve focus style consistency
  src/components/site-menu.tsx
Labels: [Type] Bug

#86 fix: Ensure non-destroyed window exists for authentication event handler
  jest.config.ts
  src/__mocks__/@sentry/electron/main.ts
  src/__mocks__/electron.ts
  src/index.ts
  src/lib/oauth.ts
  src/lib/tests/oauth.test.ts
  src/main-window.ts
  src/menu.ts
  src/tests/index.test.ts
  src/tests/main-window.test.ts
Labels: [Type] Bug

#82 Ensure only bordering areas of app are draggable
  src/components/app.tsx
  src/components/main-sidebar.tsx
  src/components/site-content-tabs.tsx
  src/components/site-menu.tsx
Labels: [Type] Enhancement, [Status] Needs Review

#94 Studio: Add translators comment for opening a website
  src/components/header.tsx
Labels: [Type] Enhancement, Studio App, Reviewer can merge

#66 Address file permission issues in new directories created by WordPress on Windows
  patches/@php-wasm+node+0.6.16.patch
Labels: [Type] Bug, [Platform] Windows

#98 Use S3 for fastlane match
  .configure
  Gemfile.lock
  fastlane/Fastfile
Labels: [Type] Enhancement, [Platform] macOS

#93 Fix: Sidebar layout breaks on specific languages
  src/components/main-sidebar.tsx
Labels: [Type] Enhancement, Studio App

#19 Add site server process
  forge.config.ts
  src/ipc-handlers.ts
  src/lib/php-get-theme-details.ts
  src/lib/site-server-process-child.ts
  src/lib/site-server-process.ts
  src/logging.ts
  src/site-server.ts
  vendor/wp-now/src/get-wp-now-path.ts
  vendor/wp-now/src/start-server.ts
  webpack.main.config.ts
Labels: [Type] Enhancement

#97 Update Studio Windows installer GIF
  installers/loading.gif
Labels: [Status] Needs Review

#102 Fix cropped focus outline style for sidebar buttons
  src/components/main-sidebar.tsx
  src/components/site-menu.tsx
Labels: [Type] Bug, Studio App, [Status] Needs Review

#73 Local Environment: Fix resolve for external hosts
  vendor/wp-now/src/download.ts
Labels: [Status] Needs Review, Reviewer can merge

#105 Update header styles
  src/components/header.tsx
Labels: [Type] Enhancement

#109 Add notarization step for release builds
  .buildkite/commands/post-process-binary-for-distribution.sh
  .buildkite/pipeline.yml
Labels: Tooling

#101 Updated Windows app icon
  assets/studio-app-icon.ico
  forge.config.ts
Labels: [Status] Needs Review

#111 Remove arrow and improve button CTA on Onboarding screen
  src/components/onboarding.tsx
  src/components/tests/onboarding.test.tsx
Labels: Studio App

#112 Release 1.0.2-beta.2
  package-lock.json
  package.json
Labels: Studio App

#123 Studio: Update "Create a free account" link to redirect to magic signup flow
  src/components/content-tab-snapshots.tsx
  src/constants.ts
  src/index.ts
  src/lib/oauth.ts
Labels: [Type] Enhancement

#128 Remove gap on the right side of Overview tab
  src/components/app.tsx
Labels: [Type] Bug, [Platform] Windows

#130 fix: Activate event window creation awaits app ready state
  src/index.ts
  src/tests/index.test.ts
Labels: [Type] Bug

#133 Update site screenshots to hide scrollbars on Windows
  src/screenshot-window.ts
Labels: [Type] Bug, [Platform] Windows

#104 Studio: Make About Studio window more compelling
  package-lock.json
  package.json
  src/about-menu/about-menu.html
  src/about-menu/open-about-menu.ts
  src/about-menu/studio-app-icon.png
  src/constants.ts
  src/menu.ts
  webpack.main.config.ts
Labels: [Type] Enhancement, [Pri] Normal

#141 Studio: Fix incorrect offline message displayed alongside "delete site" link
  src/components/delete-site.tsx
  src/components/tests/content-tab-settings.test.tsx
Labels: [Type] Bug, Studio App

#140 Exclude test environments from Sentry reporting
  src/index.ts
Labels: [Type] Enhancement, Tooling

#136 feat: Automatic sqlite-database-integration upgrade
  scripts/download-wp-server-files.ts
  src/__mocks__/fs.ts
  src/ipc-handlers.ts
  src/lib/sqlite-versions.ts
  src/setup-wp-server-files.ts
  src/tests/ipc-handlers.test.ts
  vendor/wp-now/src/constants.ts
  vendor/wp-now/src/download.ts
Labels: [Type] Enhancement

#144 Studio: Fix stop server error
  src/lib/site-server-process.ts
Labels: [Type] Bug

#150 Add AI Assistant tab
  src/components/content-tab-assistant.tsx
  src/components/site-content-tabs.tsx
  src/components/tests/content-tab-assistant.test.tsx
  src/components/tests/site-content-tabs.test.tsx
  src/hooks/use-content-tabs.ts
  src/index.css
  src/ipc-handlers.ts
  src/ipc-types.d.ts
Labels: [Type] Enhancement

#176 Don't install SQLlite on server start when it wasn't installed already
  src/ipc-handlers.ts
  src/lib/sqlite-versions.ts
  src/tests/ipc-handlers.test.ts
Labels: [Type] Bug, [Status] Needs Review

#173 Add translations for 1.0.3
  src/translations/studio-ar.jed.json
  src/translations/studio-de.jed.json
  src/translations/studio-es.jed.json
  src/translations/studio-fr.jed.json
  src/translations/studio-he.jed.json
  src/translations/studio-id.jed.json
  src/translations/studio-it.jed.json
  src/translations/studio-ja.jed.json
  src/translations/studio-ko.jed.json
  src/translations/studio-nl.jed.json
  src/translations/studio-pl.jed.json
  src/translations/studio-pt-br.jed.json
  src/translations/studio-ru.jed.json
  src/translations/studio-sv.jed.json
  src/translations/studio-tr.jed.json
  src/translations/studio-zh-cn.jed.json
  src/translations/studio-zh-tw.jed.json
Labels: Studio App

#179 test: Assert sqlite-database-integration installation
  src/tests/ipc-handlers.test.ts
Labels: [Type] Enhancement

#182 Ensure manifest output is displayed under correct group
  .buildkite/pipeline.yml
Labels: Studio App

#175 Add Assistant chat interface
  src/components/app.tsx
  src/components/content-tab-assistant.tsx
  src/components/content-tab-overview.tsx
  src/components/content-tab-settings.tsx
  src/components/content-tab-snapshots.tsx
  src/components/header.tsx
  src/components/icons/assistant.tsx
  src/components/icons/menu.tsx
  src/components/site-content-tabs.tsx
  src/components/tests/content-tab-assistant.test.tsx
  src/hooks/tests/use-assistant.test.ts
  src/hooks/use-assistant.ts
  src/index.css
Labels: [Type] Enhancement

#186 test: Delete site E2E case supports native dialogs
  e2e/page-objects/delete-site-modal.ts
  e2e/page-objects/onboarding.ts
  e2e/page-objects/settings-tab.ts
  e2e/sites.test.ts
Labels: [Type] Janitorial
