Repository Automattic/studio, pull requests merged in 2024-04, with the labels that each got.

#5 Studio: Clicking the user avatar in settings should got to their WP.com profile
  src/components/user-settings.tsx
  src/constants.ts
Labels: enhancement

#15 Add prompt for users to download correct app architecture version
  src/ipc-handlers.ts
  src/ipc-types.d.ts
  src/renderer.ts
Labels: enhancement

#12 Improve 'stop all' for long translations
  src/components/running-sites.tsx
Labels: enhancement

#13 Ensure visual start/stop cues are visible to keyboard-only users
  src/components/action-button.tsx
  src/components/site-menu.tsx
Labels: enhancement

#27 Use the OS native dialog to confirm a site deletion
  src/components/delete-site.tsx
  src/hooks/use-site-details.tsx
Labels: enhancement

#50 fix: `aria-disabled` buttons display `not-allowed` cursor
  src/components/button.tsx
Labels: bug

#57 Add copy button to demo site URL
  src/components/content-tab-snapshots.tsx
Labels: enhancement

#44 fix: Catch failed demo site status check errors
  src/hooks/tests/use-delete-snapshot.test.ts
  src/hooks/use-delete-snapshot.ts
Labels: bug

#60 Fix overflow issue for extremely long site name
  src/components/content-tab-settings.tsx
  src/components/content-tab-snapshots.tsx
  src/components/header.tsx
Labels: bug

#67 Repo Gardening: add workflow and update issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/workflows/gardening.yml
Labels: [Pri] Normal, [Type] Janitorial, [Status] Needs Review

#35 build: Upload source maps to Sentry
  .gitignore
  package-lock.json
  package.json
  webpack.main.config.ts
  webpack.plugins.ts
  webpack.renderer.config.ts
Labels: [Type] Enhancement

#4 fix: Improve site creation error handling
  src/components/site-form.tsx
  src/components/tests/add-site.test.tsx
  src/hooks/use-add-site.ts
  src/ipc-handlers.ts
Labels: [Type] Bug
