Repository Automattic/studio, pull requests merged in 2024-10, with the labels that each got.

#565 Try to stop server if site initialization failed
  src/components/tests/header.test.tsx
  src/hooks/use-site-details.tsx
  src/lib/site-server-process-child.ts
Labels: [Type] Bug, [Status] Needs Review

#580 Update `@php-wasm/universal` patch
  patches/@php-wasm+universal+0.9.44.patch
Labels: [Type] Bug, [Status] Needs Review

#583 Issue templates: add new issue type option
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: [Type] Enhancement

#579 Include original error message in error message box
  src/components/assistant-anchor.tsx
  src/components/delete-site.tsx
  src/components/tests/assistant-anchor.test.tsx
  src/components/tests/header.test.tsx
  src/hooks/tests/use-import-export.test.tsx
  src/hooks/tests/use-update-demo-site.test.tsx
  src/hooks/use-archive-site.ts
  src/hooks/use-import-export.tsx
  src/hooks/use-site-details.tsx
  src/hooks/use-update-demo-site.tsx
  src/ipc-handlers.ts
  src/preload.ts
Labels: [Type] Enhancement

#596 Ensure Windows' application menu button is always visible by leaving space for window controls
  src/components/windows-titlebar.tsx
  tailwind.config.js
Labels: [Type] Bug, [Status] Needs Review, Reviewer can merge

#603 Ensure Mac's titlebar padding always leaves space for the window controls
  src/components/app.tsx
  src/components/mac-titlebar.tsx
  src/components/main-sidebar.tsx
  src/components/site-menu.tsx
  src/components/windows-titlebar.tsx
  src/lib/is-window-frame-rtl.ts
  tailwind.config.js
Labels: [Type] Bug, [Status] Needs Review, Reviewer can merge
