Repository Automattic/studio, pull requests merged in 2024-06, with the labels that each got.

#200 Add Assistant Markdown parsing using react-markdown
  package-lock.json
  package.json
  src/__mocks__/react-markdown.ts
  src/components/content-tab-assistant.tsx
  src/components/tests/content-tab-assistant.test.tsx
  src/index.css
Labels: [Type] Enhancement

#202 Update AI Assistant Input component
  src/components/ai-input.tsx
  src/components/content-tab-assistant.tsx
  src/components/icons/assistant.tsx
  src/components/icons/menu.tsx
  src/components/icons/return.tsx
  src/components/tests/ai-input.test.tsx
  src/components/tests/content-tab-assistant.test.tsx
Labels: [Type] Enhancement

#195 Studio: Reclaim unavailable port after site deletion
  package-lock.json
  package.json
  src/lib/port-finder.ts
  src/site-server.ts
Labels: Studio App

#210 Update Assistant-related icons
  src/components/ai-input.tsx
  src/components/icons/assistant.tsx
  src/components/icons/menu.tsx
  src/components/icons/return.tsx
Labels: [Type] Enhancement

#208 Update Assistant Markdown styles
  src/components/content-tab-assistant.tsx
  src/index.css
Labels: [Type] Enhancement

#197 Studio: Add prompt limit UI
  src/components/root.tsx
  src/components/tests/user-settings.test.tsx
  src/components/user-settings.tsx
  src/constants.ts
  src/hooks/tests/use-assistant-api.test.ts
  src/hooks/use-assistant-api.ts
  src/hooks/use-prompt-usage.tsx
Labels: [Status] Needs Review, Studio AI Assistant

#227 Release 1.0.4-beta1
  package-lock.json
  package.json
Labels: Studio App

#199 Studio: Update wp-cli
  src/lib/wpcli-versions.ts
  src/setup-wp-server-files.ts
  src/tests/execute-wp-cli.test.ts
  vendor/wp-now/src/download.ts
  vendor/wp-now/src/execute-wp-cli.ts
  vendor/wp-now/src/get-wp-cli-path.ts
  vendor/wp-now/src/tests/wp-now.spec.ts
Labels: [Status] Needs Review, Studio AI Assistant

#214 Add UI for dynamic code block to execute Assistant wp-cli commands
  src/components/button.tsx
  src/components/content-tab-assistant.tsx
  src/components/icons/execute.tsx
  src/index.css
Labels: [Type] Enhancement

#228 Studio: Translate "About Studio" modal
  src/about-menu/about-menu.html
  src/about-menu/open-about-menu.ts
Labels: Studio App

#221 Iterate on launch stats, to include tracking for all and first-time launches
  src/index.ts
  src/lib/bump-stats.ts
  src/lib/tests/bump-stats.test.ts
Labels: Studio App, [Status] Needs Review, [Status] Not Ready for Merge

#211 Allow user to speed up sites on Windows programmatically
  package-lock.json
  package.json
  src/components/onboarding.tsx
  src/ipc-handlers.ts
  src/lib/windows-helpers.ts
  src/menu.ts
  src/preload.ts
  src/storage/storage-types.ts
Labels: [Status] Needs Copy Review, [Status] Editorial Input Requested

#235 Update rendered Markdown styles
  src/components/content-tab-assistant.tsx
  src/index.css
Labels: Studio AI Assistant

#243 fix: Improve button style consistency
  src/components/add-site.tsx
  src/components/button.tsx
  src/components/content-tab-assistant.tsx
Labels: [Type] Bug

#246 fix: Prevent resubmissions of pending site addition
  src/components/add-site.tsx
  src/components/tests/add-site.test.tsx
Labels: [Type] Bug

#244 Studio: Disable text input if the limit is reached UI and update to new headers
  src/components/content-tab-assistant.tsx
  src/components/user-settings.tsx
  src/hooks/use-assistant-api.ts
  src/hooks/use-prompt-usage.tsx
Labels: Studio AI Assistant

#230 Studio: Studio: Log all the messages for performance analysis
  src/components/content-tab-assistant.tsx
  src/hooks/tests/use-assistant-api.test.ts
  src/hooks/use-assistant-api.ts
  src/hooks/use-assistant.ts
Labels: [Status] Needs Review, Studio AI Assistant

#245 Studio: Add the initial welcome prompts UI component
  src/components/content-tab-assistant.tsx
  src/components/tests/content-tab-assistant.test.tsx
  src/components/welcome-message-prompt.tsx
  src/hooks/use-fetch-welcome-messages.ts
Labels: Studio AI Assistant

#249 feat: Assistant renders Markdown tables
  package-lock.json
  package.json
  src/__mocks__/remark-gfm.ts
  src/components/content-tab-assistant.tsx
  src/index.css
Labels: [Type] Enhancement

#250 Studio: Add UI for clearing chat messages
  src/components/ai-input.tsx
  src/components/tests/ai-input.test.tsx
  src/components/tests/content-tab-assistant.test.tsx
Labels: Studio AI Assistant

#253 docs: Organize and expand contributing documentation
  CONTRIBUTING.md
  README.md
  docs/code-contributions.md
Labels: [Type] Documentation

#248 feat: Improve AI assistant accessibility
  src/components/assistant-thinking.tsx
  src/components/content-tab-assistant.tsx
  src/components/icons/assistant.tsx
Labels: [Type] Enhancement

#261 feat: Open assistant-generated links in a browser
  src/components/content-tab-assistant.tsx
Labels: [Type] Enhancement

#260 Studio: AssistantIsThinking triggrers across multiple sites
  src/components/content-tab-assistant.tsx
  src/hooks/tests/use-assistant-api.test.ts
  src/hooks/use-assistant-api.ts
Labels: Studio AI Assistant

#259 Studio: creating a new site pulls assistant messages from another site
  src/hooks/tests/use-assistant.test.ts
  src/hooks/use-assistant.ts
Labels: Studio AI Assistant

#257 Studio: Fix wp-cli command for linux
  bin/wp
  src/ipc-handlers.ts
Labels: Studio AI Assistant

#213 feat: Invoke `wp-cli` from terminal sessions originating from Studio
  bin/wp
  bin/wp.bat
  forge.config.ts
  package-lock.json
  package.json
  src/__mocks__/electron.ts
  src/index.ts
  src/ipc-handlers.ts
  src/lib/cli.ts
  src/preload.ts
  vendor/wp-now/src/execute-wp-cli.ts
Labels: [Type] Enhancement

#252 Studio: Add chat context
  src/components/content-tab-assistant.tsx
  src/components/root.tsx
  src/hooks/use-assistant-api.ts
  src/hooks/use-chat-context.tsx
  src/ipc-handlers.ts
  src/lib/cli.ts
  src/lib/is-installed.ts
  src/lib/windows-helpers.ts
  vendor/wp-now/src/execute-wp-cli.ts
Labels: Studio AI Assistant

#275 fix: Reinstate Assistant a11y message groups
  src/components/chat-message.tsx
  src/components/content-tab-assistant.tsx
  src/components/copy-text-button.tsx
  src/components/welcome-message-prompt.tsx
Labels: [Type] Bug, Studio AI Assistant

#274 feat: Limit Assistant chat visibility to participants
  src/components/auth-provider.tsx
  src/components/content-tab-assistant.tsx
  src/components/tests/content-tab-assistant.test.tsx
  src/hooks/use-assistant.ts
  src/lib/oauth.ts
Labels: [Type] Enhancement, Studio AI Assistant

#281 fix: Prevent invalid code markup
  src/components/chat-message.tsx
Labels: [Type] Bug

#287 feat: Permanently dismiss clear messages warning
  src/components/ai-clear-history-reminder.tsx
  src/components/ai-input.tsx
  src/components/tests/ai-clear-history-reminder.test.tsx
  src/components/tests/ai-input.test.tsx
Labels: [Type] Enhancement, Studio AI Assistant

#291 feat: Improve dialog messaging consistency
  src/components/content-tab-snapshots.tsx
Labels: [Type] Enhancement

#283 Studio: Images arent loaded in assistant responses
  src/components/chat-message.tsx
Labels: Studio AI Assistant

#292 feat: Limit permanent warning dismissal to affirmative actions
  src/components/ai-clear-history-reminder.tsx
  src/components/ai-input.tsx
  src/components/content-tab-snapshots.tsx
  src/renderer.ts
Labels: [Type] Enhancement

#294 feat: Avoid Assistant navigating to stopped sites
  src/components/chat-message.tsx
Labels: [Type] Enhancement, Studio AI Assistant

#295 feat: Minimize site form layout shift
  src/components/site-form.tsx
Labels: [Type] Enhancement

#298 Studio: Make assistant input container transparent
  src/components/ai-clear-history-reminder.tsx
  src/components/ai-input.tsx
  src/components/app.tsx
  src/components/content-tab-assistant.tsx
  src/index.css
Labels: [Type] Enhancement, Studio AI Assistant

#284 Track first app launches
  src/index.ts
  src/lib/bump-stats.ts
  src/lib/tests/bump-stats.test.ts
Labels: Studio App, [Status] Needs Review

#305 test: Assert Assistant code block
  jest-setup.ts
  src/__mocks__/strip-ansi.ts
  src/components/assistant-code-block.tsx
  src/components/chat-message.tsx
  src/components/tests/assistant-code-block.test.tsx
Labels: [Type] Janitorial, Studio AI Assistant

#306 Studio: Block the text input when sending
  src/components/ai-input.tsx
  src/components/content-tab-assistant.tsx
Labels: Studio AI Assistant

#313 test: Assert Assistant anchor
  src/components/assistant-anchor.tsx
  src/components/chat-message.tsx
  src/components/tests/assistant-anchor.test.tsx
Labels: [Type] Janitorial, Studio AI Assistant

#318 Removes reference to Windows waiting list
  README.md
Labels: OSS Citizen

#316 test: Reduce output noise
  jest-setup.ts
  src/components/tests/assistant-code-block.test.tsx
  src/tests/execute-wp-cli.test.ts
Labels: [Type] Janitorial

#317 feat: Improve Assistant prompt accessibility
  src/components/ai-input.tsx
  src/components/content-tab-assistant.tsx
  src/components/tests/ai-input.test.tsx
  src/components/tests/content-tab-assistant.test.tsx
  src/components/welcome-message-prompt.tsx
Labels: [Type] Documentation, Studio AI Assistant

#314 Studio: Unable to send messages to AI when switching sites
  src/components/tests/content-tab-assistant.test.tsx
  src/hooks/tests/use-assistant.test.ts
  src/hooks/use-assistant.ts
Labels: Studio AI Assistant
