Repository Automattic/studio, pull requests merged in 2024-11, with the labels that each got.

#667 fix: More suggestions button communicates focus
  src/components/welcome-message-prompt.tsx
Labels: [Type] Bug

#671 Limit arm translation modal to mac
  src/renderer.ts
Labels: Reviewer can merge

#676 Allow theme and plugin list generation to fail gracefully
  src/lib/import-export/export/exporters/default-exporter.ts
  src/lib/import-export/tests/export/exporters/default-exporter.test.ts
Labels: Studio App
