Repository Automattic/studio, pull requests merged in 2025-05, with the labels that each got.

#1302 Don't capture Wasm memory errors in Sentry
  src/ipc-handlers.ts
Labels: Bug

#1358 Persist preferred locale
  src/hooks/use-i18n-data.tsx
  src/modules/user-settings/components/preferences-tab.tsx
Labels: Reviewer can merge

#1367 Ignore .git & node_modules in preview archive
  cli/lib/archive.ts
  cli/lib/tests/archive.test.ts
Labels: OSS Citizen

#1400 HTTPS: Convert domain name Unicode characters to ASCII characters
  src/lib/certificate-manager.ts
Labels: Reviewer can merge

#1408 [Tooling] Update code to DRY the Windows build PS1
  .buildkite/commands/build-for-windows-dev.ps1
  .buildkite/commands/build-for-windows-release.ps1
  .buildkite/commands/build-for-windows.ps1
  .buildkite/pipeline.yml
  package.json
Labels: tooling
