Repository Automattic/studio, pull requests merged in 2025-03, with the labels that each got.

#993 Update tooltips in the new Previews tab
  src/components/sync-connected-sites.tsx
  src/hooks/use-expiration-date.ts
  src/modules/preview-site/components/preview-site-row.tsx
Labels: OSS Citizen, Enhancement

#1027 Update tooltips in the new Previews tab (redo)
  src/components/sync-connected-sites.tsx
  src/hooks/use-expiration-date.ts
  src/modules/preview-site/components/preview-site-row.tsx
Labels: OSS Citizen, Enhancement

#1029 Use WP Zip URL on wp core update to support betas in different locales
  src/lib/get-wordpress-version-url.ts
  src/modules/site-settings/edit-site-details.tsx
  src/modules/site-settings/tests/edit-site-details.test.tsx
  vendor/wp-now/src/download.ts
Labels: Reviewer can merge

#1032 [Tooling] Update Buildkite Plugins
  .buildkite/shared-pipeline-vars
Labels: tooling

#994 STU-22: Add custom local domain support for WordPress sites
  package-lock.json
  package.json
  src/components/add-site.tsx
  src/components/content-tab-settings.tsx
  src/components/onboarding.tsx
  src/components/site-form.tsx
  src/components/tests/add-site.test.tsx
  src/components/tests/onboarding.test.tsx
  src/hooks/tests/use-add-site.test.tsx
  src/hooks/use-add-site.ts
  src/hooks/use-site-details.tsx
  src/index.ts
  src/ipc-handlers.ts
  src/ipc-types.d.ts
  src/lib/generate-custom-domain.ts
  src/lib/hosts-file.ts
  src/lib/proxy-server.ts
  src/lib/tests/hosts-file.test.ts
  src/preload.ts
  src/site-server.ts
  src/storage/user-data.ts
  src/tests/index.test.ts
  src/tests/ipc-handlers.test.ts
Labels: Enhancement

#1064 Custom Domain: Allow updating domains for existing sites.
  src/components/add-site.tsx
  src/components/site-form.tsx
  src/hooks/use-add-site.ts
  src/ipc-handlers.ts
  src/lib/domains.ts
  src/lib/generate-custom-domain.ts
  src/lib/hosts-file.ts
  src/lib/import-export/import/importers/importer.ts
  src/lib/tests/hosts-file.test.ts
  src/lib/update-site-url-to-local.ts
  src/modules/site-settings/edit-site-details.tsx
  src/site-server.ts
Labels: Enhancement

#1116 Site updates: Regenerate domain certificate when the domain is changed
  src/ipc-handlers.ts
  src/lib/certificate-manager.ts
  src/lib/import-export/tests/import/import-manager.test.ts
  src/site-server.ts
Labels: Bug

#1119 Performance metrics: Bootstrap the test
  .gitignore
  metrics/README.md
  metrics/performance-reporter.ts
  metrics/playwright.metrics.config.ts
  metrics/tests/site-startup.test.ts
  metrics/utils.ts
  package.json
Labels: tooling

#1123 Performance metrics: Add a CI job to compare the performance of PR branches with trunk
  .buildkite/pipeline.yml
  .github/workflows/metrics-comparison.yml
  e2e/e2e-helpers.ts
  metrics/README.md
  metrics/performance-reporter.ts
  metrics/playwright.metrics.config.ts
  metrics/tests/site-startup.test.ts
  package.json
  scripts/compare-perf/config.ts
  scripts/compare-perf/index.ts
  scripts/compare-perf/package-lock.json
  scripts/compare-perf/package.json
  scripts/compare-perf/performance.ts
  scripts/compare-perf/utils.ts
  src/lib/sqlite-command-release.ts
Labels: tooling

#1145 Fix Studio launch after recent mac install script was added
  src/modules/cli/lib/install-macos.ts
Labels: Bug

#1143 Revert tmp code from #1123
  .github/workflows/metrics-comparison.yml
  e2e/e2e-helpers.ts
  metrics/playwright.metrics.config.ts
  metrics/tests/site-startup.test.ts
Labels: tooling

#1147 Update SQLite database integration plugin to v2.1.19-alpha
  src/constants.ts
Labels: [Status] Needs Review, Enhancement

#1144 Performance Metrics: Log the results in codevitals
  .github/workflows/metrics-comparison.yml
  metrics/README.md
  scripts/compare-perf/log-to-codevitals.ts
  scripts/compare-perf/package.json
Labels: tooling

#1155 Update SQLite database integration plugin to v2.1.17-alpha.1
  src/constants.ts
  src/lib/sqlite-versions.ts
Labels: Bug
