Repository Automattic/studio, pull requests merged in 2025-04, with the labels that each got.

#1162 Performance Metrics: Add site editor load perf tests
  metrics/README.md
  metrics/tests/site-editor.test.ts
  scripts/compare-perf/log-to-codevitals.ts
Labels: tooling

#1130 Implement studio go for creating preview sites
  cli/commands/preview/create.ts
  cli/commands/preview/lib/api.ts
  cli/commands/preview/lib/appdata.ts
  cli/commands/preview/lib/archive.ts
  cli/commands/preview/lib/auth.ts
  cli/commands/preview/lib/validation.ts
  cli/commands/preview/tests/api.test.ts
  cli/commands/preview/tests/appdata.test.ts
  cli/commands/preview/tests/archive.test.ts
  cli/commands/preview/tests/auth.test.ts
  cli/commands/preview/tests/create.test.ts
  cli/commands/preview/tests/validation.test.ts
  cli/logger.ts
  cli/package.json
  package-lock.json
  package.json
  webpack.cli.config.ts
Labels: Reviewer can merge

#1214 Check for prerelease versions when copying the bundled SQLite plugin
  src/setup-wp-server-files.ts
Labels: Bug

#1233 Update Electron and Node versions
  .nvmrc
  package-lock.json
  package.json
Labels: Enhancement

#1277 Improve the alignment of the "More options" dropdown
  src/components/content-tab-settings.tsx
Labels: OSS Citizen
