Repository Automattic/studio, pull requests merged in 2025-01, with the labels that each got.

#809 Mount symlinks when executing WP-cli commands
  src/lib/symlink-manager.ts
  src/lib/tests/symlink-manage.test.ts
  src/lib/wpcli-versions.ts
  vendor/wp-now/src/execute-wp-cli.ts
  vendor/wp-now/src/get-wp-cli-path.ts
  vendor/wp-now/src/wp-now.ts
Labels: [Type] Bug, [Pri] Normal, Studio Compatibility Boost i2

#852 Include mu-plugins in Studio site import
  src/lib/import-export/import/importers/importer.ts
  src/lib/import-export/import/types.ts
  src/lib/import-export/import/validators/jetpack-validator.ts
  src/lib/import-export/import/validators/local-validator.ts
  src/lib/import-export/import/validators/playground-validator.ts
  src/lib/import-export/import/validators/wpress-validator.ts
  src/lib/import-export/tests/import/validators/jetpack-validator.test.ts
  src/lib/import-export/tests/import/validators/local-validator.test.ts
  src/lib/import-export/tests/import/validators/playground-validator.test.ts
Labels: [Type] Enhancement

#860 Remove internal mu-plugins during prepareWordPress
  vendor/wp-now/src/wp-now.ts
Labels: [Type] Bug

#868 change release naming for Sentry
  src/index.ts
  src/lib/app-globals.ts
  src/lib/sentry-release.ts
  webpack.plugins.ts
Labels: Reviewer can merge
